version: '3'

services:

  # Server Service
  server:
    image: server
    build: .
    network_mode: host
    environment:
      - PORT=5000
      - FLASK_ENV=development
    ports:
     - "5000:5000"
    # # This service depends on the databse to run
    # depends_on:
    #   - database
    volumes:
      - ./server:/root/server:cached
  
  # DataBase Service (MariaDB)
  database:
    image: mariadb
    build: ./sql
    network_mode: host
    ports:
      - "3306:3306"
    # command: cd sql
    # volumes:
    #   - ./sql/scanner.sql:/data/app/sql/scanner.sql
    #   - ./sql:/root/sql:cached
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: apkscanner
      MYSQL_USER: appsentinel
      MYSQL_PASSWORD: teste123
    # restart: on-failure